version: "2.4"
services:
  mgt01:
    image: cloudstack-management:ubuntu1604
    hostname: mgt01
    networks:
        {{ bridge }}:
            ipv4_address: {{ mgt01_ip }}
    volumes:
        - {{ dir }}/packages:/root/packages
        - {{ dir }}/mgt01/log:/var/log/cloudstack/
        - {{ dir }}/mgt01/etc:/etc/cloudstack/
    healthcheck:
        test: ["CMD", "/usr/bin/cmk", "list", "accounts", "filter=name"]
        interval: {{ check_interval }}s
        timeout: {{ check_timeout }}s
        retries: {{ check_retries }}
        start_period: {{ check_interval }}s
    environment:
      - CLOUDSTACK_VERSION=4.14.0.0~bionic
      - MYSQL_ADDRESS={{ db_vip }}
      - MYSQL_ROOT_PASSWORD=cloudstack
      - MYSQL_CLOUD_PASSWORD=cloudstack
      - MANAGEMENT_KEY=mgtKey
      - DATABASE_KEY=dbKey
      - SYSTEMVM_TEMPLATE=http://download.cloudstack.org/systemvm/4.14/systemvmtemplate-4.14.0-kvm.qcow2.bz2
      - ADMIN_PASSWORD=cloudstack
      - NODE_NAME=mgt01
    command: setup

  mgt02:
    image: cloudstack-management:ubuntu1604
    hostname: mgt02
    depends_on:
        mgt01:
            condition: service_healthy
    networks:
        {{ bridge }}:
            ipv4_address: {{ mgt02_ip }}
    volumes:
        - {{ dir }}/packages:/root/packages
        - {{ dir }}/mgt02/log:/var/log/cloudstack/
        - {{ dir }}/mgt02/etc:/etc/cloudstack/
    environment:
      - CLOUDSTACK_VERSION=4.14.0.0~bionic
      - MYSQL_ADDRESS={{ db_vip }}
      - MYSQL_ROOT_PASSWORD=cloudstack
      - MYSQL_CLOUD_PASSWORD=cloudstack
      - MANAGEMENT_KEY=mgtKey
      - DATABASE_KEY=dbKey
      - SYSTEMVM_TEMPLATE=http://download.cloudstack.org/systemvm/4.14/systemvmtemplate-4.14.0-kvm.qcow2.bz2
      - ADMIN_PASSWORD=cloudstack
      - NODE_NAME=mgt02
    command: install

  mgt03:
    image: cloudstack-management:ubuntu1604
    hostname: mgt03
    depends_on:
        mgt01:
            condition: service_healthy
    networks:
        {{ bridge }}:
            ipv4_address: {{ mgt03_ip }}
    volumes:
        - {{ dir }}/packages:/root/packages
        - {{ dir }}/mgt03/log:/var/log/cloudstack/
        - {{ dir }}/mgt03/etc:/etc/cloudstack/
    environment:
      - CLOUDSTACK_VERSION=4.14.0.0~bionic
      - MYSQL_ADDRESS={{ db_vip }}
      - MYSQL_ROOT_PASSWORD=cloudstack
      - MYSQL_CLOUD_PASSWORD=cloudstack
      - MANAGEMENT_KEY=mgtKey
      - DATABASE_KEY=dbKey
      - SYSTEMVM_TEMPLATE=http://download.cloudstack.org/systemvm/4.14/systemvmtemplate-4.14.0-kvm.qcow2.bz2
      - ADMIN_PASSWORD=cloudstack
      - NODE_NAME=mgt03
    command: install

  mgtvip:
    image: nginx
    hostname: mgtvip
    ports:
        - "8080:8080"
    networks:
        {{ bridge }}:
            ipv4_address: {{ mgt_vip }}
    volumes:
        - {{ dir }}/nginx-cloudstack.conf:/etc/nginx/nginx.conf

networks:
  {{ bridge }}:
    external:
      name: {{ bridge }}
