version: "2"
services:
  mgt01:
    image: cloudstack-management:ubuntu1604
    hostname: mgt01
    networks:
        breth1:
            ipv4_address: {{ mgt01_ip }}
    volumes:
        - {{ dir }}/packages:/root/packages
    environment:
      - CLOUDSTACK_VERSION=4.14.0.0~bionic
      - MYSQL_ADDRESS={{ db_vip }}
      - MYSQL_ROOT_PASSWORD=cloudstack
      - MYSQL_CLOUD_PASSWORD=cloudstack
      - MANAGEMENT_KEY=mgtKey
      - DATABASE_KEY=dbKey
      - SYSTEMVM_TEMPLATE=http://download.cloudstack.org/systemvm/4.14/systemvmtemplate-4.14.0-kvm.qcow2.bz2
      - ADMIN_PASSWORD=cloudstack
      - NODE_NAME=mgt01
    command: setup

networks:
  breth1:
    external:
      name: {{ bridge }}
