version: "2"
services:
  db01:
    image: hauptmedia/mariadb:10.1
    hostname: db01
    networks:
        breth1:
            ipv4_address: {{ db01_ip }}
    volumes:
        - /root/docker/db01:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cloudstack
      - REPLICATION_PASSWORD=cloudstack
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=cloudstack
      - GALERA=On
      - NODE_NAME=db01
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://

  db02:
    image: hauptmedia/mariadb:10.1
    hostname: db02
    depends_on:
      - db01
    links:
      - db01
    networks:
        breth1:
            ipv4_address: {{ db02_ip }}
    volumes:
        - /root/docker/db02:/var/lib/mysql
    environment:
      - REPLICATION_PASSWORD=cloudstack
      - GALERA=On
      - NODE_NAME=db02
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      
  db03:
    image: hauptmedia/mariadb:10.1
    hostname: db03
    depends_on:
      - db01
    links:
      - db01
    networks:
        breth1:
            ipv4_address: {{ db03_ip }}
    volumes:
        - /root/docker/db03:/var/lib/mysql
    environment:
      - REPLICATION_PASSWORD=cloudstack
      - GALERA=On
      - NODE_NAME=db03
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03

  dbvip:
    image: nginx
    hostname: dbvip
    depends_on:
      - db01
      - db02
      - db03
    links:
      - db01
      - db02
      - db03
    networks:
        breth1:
            ipv4_address: {{ db_vip }}
    volumes:
        - /root/docker/nginx.conf:/etc/nginx/nginx.conf

networks:
    breth1:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: "breth1"
        ipam:
            driver: default
            config:
                - subnet: {{ subnet }}
                  iprange: {{ subnet }}
                  gateway: {{ host_ip }}
