version: "2.4"
services:
  db01:
    image: hauptmedia/mariadb:10.1
    hostname: db01
    networks:
        {{ bridge }}:
            ipv4_address: {{ db01_ip }}
    volumes:
      - {{ dir }}/db01:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cloudstack
      - REPLICATION_PASSWORD=cloudstack
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=cloudstack
      - GALERA=On
      - NODE_NAME=db01
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
    command: --wsrep-new-cluster

  db02:
    image: hauptmedia/mariadb:10.1
    hostname: db02
    depends_on:
      - db01
    networks:
        {{ bridge }}:
            ipv4_address: {{ db02_ip }}
    volumes:
      - {{ dir }}/db02:/var/lib/mysql
    environment:
      - REPLICATION_PASSWORD=cloudstack
      - GALERA=On
      - NODE_NAME=db02
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      
  db03:
    image: hauptmedia/mariadb:10.1
    hostname: db03
    depends_on:
      - db01
    networks:
        {{ bridge }}:
            ipv4_address: {{ db03_ip }}
    volumes:
      - {{ dir }}/db03:/var/lib/mysql
    environment:
      - REPLICATION_PASSWORD=cloudstack
      - GALERA=On
      - NODE_NAME=db03
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03

  dbvip:
    image: nginx
    hostname: dbvip
    networks:
        {{ bridge }}:
            ipv4_address: {{ db_vip }}
    volumes:
      - {{ dir }}/nginx-galera.conf:/etc/nginx/nginx.conf

networks:
  {{ bridge }}:
    external:
      name: {{ bridge }}
